export enum StatisticsType {
  FIND_FILE_BY_ID = 'FIND_FILE_BY_ID',
  FIND_MANY_FILES = 'FIND_MANY_FILES',
  FIND_DOWNLOAD_BY_ID = 'FIND_DOWNLOAD_BY_ID',
  FIND_MANY_DOWNLOADS = 'FIND_MANY_DOWNLOADS',
  SAVE_FILE = 'SAVE_FILE',
  START_DOWNLOAD = 'START_DOWNLOAD',
  FINISH_DOWNLOAD = 'FINISH_DOWNLOAD',
  CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD',
}
