# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Bootsrap packages
      run: npm run bootstrap

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

    - name: E2E test
      run: npm run test:e2e
